version: '3'
services: 
  web:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend/package.json:/app/package.json
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src 
  server:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"